"""empty message

Revision ID: 3e40fc97089c
Revises: 721b538f2b40
Create Date: 2022-08-24 15:55:57.615026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e40fc97089c'
down_revision = '721b538f2b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('res_date_start', sa.Date(), nullable=False))
    op.add_column('reservations', sa.Column('res_date_end', sa.Date(), nullable=False))
    op.drop_column('reservations', 'res_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('res_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'res_date_end')
    op.drop_column('reservations', 'res_date_start')
    # ### end Alembic commands ###
