"""empty message

Revision ID: 32ac711eb336
Revises: 5454946abe65
Create Date: 2022-08-02 11:15:17.609303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ac711eb336'
down_revision = '5454946abe65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('locations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_1_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_2_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('campsite_info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('essential_info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amenities_info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details_info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='locations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='locations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommends', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='reviews_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    # ### end Alembic commands ###
