"""empty message

Revision ID: 721b538f2b40
Revises: c9320e331e2c
Create Date: 2022-08-24 15:53:04.480148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721b538f2b40'
down_revision = 'c9320e331e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('res_date_start', sa.Date(), nullable=False),
    sa.Column('res_date_end', sa.Date(), nullable=False),

    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
